(function(){
const reactionNames={fire:'Fire',w:'W',lol:'LOL'};let selectedReaction=null;
async function reactions(){const actions=document.getElementById('actions');if(!actions||!window.clip)return;let box=document.getElementById('clip-reactions');if(!box){box=document.createElement('div');box.id='clip-reactions';box.style.cssText='display:flex;gap:7px;flex-wrap:wrap;margin:-6px 0 18px';actions.after(box)}const {data}=await client.from('clip_reactions').select('reaction,user_id').eq('clip_id',clip.id);const rows=data||[];const counts=Object.fromEntries(Object.keys(reactionNames).map(k=>[k,0]));rows.forEach(r=>{if(counts[r.reaction]!==undefined)counts[r.reaction]++});selectedReaction=window.me?rows.find(r=>r.user_id===window.me.id)?.reaction||null:null;box.innerHTML=Object.keys(reactionNames).map(k=>'<button class="btn '+(selectedReaction===k?'btn-green':'btn-outline')+' reaction-btn" data-reaction="'+k+'">'+reactionNames[k]+' '+counts[k]+'</button>').join('');box.querySelectorAll('.reaction-btn').forEach(b=>b.onclick=()=>toggleReaction(b.dataset.reaction))}
async function toggleReaction(type){const me=window.me||await getCurrentUser();if(!me){location.href='login.html';return}if(selectedReaction===type){await client.from('clip_reactions').delete().eq('clip_id',clip.id).eq('user_id',me.id)}else{await client.from('clip_reactions').upsert({clip_id:clip.id,user_id:me.id,reaction:type},{onConflict:'clip_id,user_id'});};await reactions()}
async function replies(){if(typeof window.loadComments!=='function')return;const old=window.loadComments;window.loadComments=async function(){await old();const list=document.getElementById('comment-list');if(!list||!window.clip)return;const {data:comments}=await client.from('comments').select('id,content,created_at,user_id,parent_id').eq('clip_id',clip.id).order('created_at',{ascending:true});if(!comments?.length)return;const ids=[...new Set(comments.map(c=>c.user_id))];const {data:ps}=await client.from('profiles').select('id,username,display_name,is_dev,verified').in('id',ids);const pm=Object.fromEntries((ps||[]).map(p=>[p.id,p]));const children=comments.filter(c=>c.parent_id);const roots=comments.filter(c=>!c.parent_id);list.innerHTML=roots.map(c=>commentHtml(c,pm,children)).join('')||list.innerHTML;list.querySelectorAll('[data-reply-id]').forEach(b=>b.onclick=()=>replyTo(b.dataset.replyId));}
}
function commentHtml(c,pm,children){const p=pm[c.user_id]||{},n=escapeHtml(p.display_name||p.username||'user'),v=p.verified?' <span class="verified-badge">VERIFIED</span>':'';let html='<div class="comment"><div class="who">@'+escapeHtml(p.username||'user')+v+'</div><div>'+escapeHtml(c.content)+'</div><button class="btn btn-outline" style="margin-top:8px;padding:5px 9px;font-size:11px" data-reply-id="'+c.id+'">Reply</button>';const kids=children.filter(x=>x.parent_id===c.id);if(kids.length)html+='<div class="comment-replies" style="margin:10px 0 0 18px;display:grid;gap:8px">'+kids.map(k=>'<div class="comment"><div class="who">@'+escapeHtml(pm[k.user_id]?.username||'user')+'</div><div>'+escapeHtml(k.content)+'</div></div>').join('')+'</div>';return html+'</div>'}
async function replyTo(id){const me=await requireLogin();if(!me)return;const text=prompt('Reply to this comment');if(!text?.trim())return;try{ClipNowModeration.assertTextAllowed(text.trim(),'comment')}catch(e){alert(e.message);return}const {error}=await client.from('comments').insert({clip_id:clip.id,user_id:me.id,parent_id:id,content:text.trim()});if(error){alert(error.message);return}await window.loadComments()}
function tags(){if(!window.clip)return;const d=document.getElementById('description');if(!d||!clip.tags?.length)return;let box=document.getElementById('clip-tags');if(!box){box=document.createElement('div');box.id='clip-tags';box.style.cssText='display:flex;gap:6px;flex-wrap:wrap;margin:-14px 0 20px'}box.innerHTML=clip.tags.slice(0,8).map(t=>'<a href="discover.html?tag='+encodeURIComponent(t)+'" class="tag-chip">#'+escapeHtml(t)+'</a>').join('');d.after(box)}
window.addEventListener('load',()=>{setTimeout(()=>{reactions();replies();tags()},600)})
})();